# Generated by Django 4.1.6 on 2023-08-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_product3_author_product3_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product3',
            name='date',
        ),
    ]
