# Generated by Django 4.1.6 on 2023-08-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_product3_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product2',
            name='date',
        ),
        migrations.AddField(
            model_name='product2',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product2',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product2',
            name='image',
            field=models.ImageField(upload_to='products3/%Y/%m/%d'),
        ),
    ]
